#!/bin/sh

STORAGE="$HOME/.local/share/mpdstates/"
# yes, this is a butchering of pipes and scripting.
MPDSTATE=$(cat ~/.config/mpd/mpd.conf | grep -E "^state_file" | grep -o "\"/.*\"" | sed -e "s|\"||" -e "s|\"$||")
TMPFILE="/tmp/mpdstate.temp"

HELPSTRING=$(
cat << EOF
\tld\tLoad state (arg1).\n
\tsv\tSave current state as (arg1).\n
\tls\tList all saved states.\n
\trm\tRemove (arg1) saved state."\n
\tmv\tRename (arg1) saved state to (arg2)\n
EOF
)


echo 
# test if $1 is empty or not
exists(){
    if [ $1"" = "" ]; then 
        echo -e $2 
        exit 1
    fi
}

# the time it takes for mpd to start again
pause(){
    sleep 0.2
}

# make the storage if it doesn't exist
if [ ! -e $STORAGE ]; then 
    mkdir $STORAGE   
fi


exists "$1" "\tNeeds arguments,\n""$HELPSTRING"



# SAVE a playlist
if [ $1 = "sv" ]; then
    exists "$2" "needs name."    
    mpd --kill
    cp $MPDSTATE $STORAGE""$2
    pause
    mpd
    exit 0;
fi

# LOAD a playlist ()
if [ $1 = "ld" ]; then
    exists "$2" "which state to load?"    
    STATE=$STORAGE""$2
    if [ ! -e $STATE ]; then
        echo $2" doesn't exist."
        exit 0;
    fi
    mpd --kill
    cp $MPDSTATE $TMPFILE
    cp $STATE $MPDSTATE
    mv $TMPFILE $STORAGE"old"
    pause
    mpd
    exit 0;
fi

# LIST states
if [ $1 = "ls" ]; then
    ls $STORAGE
    exit 0;
fi

# REMOVE state
if [ $1 = "rm" ]; then 
    exists "$2" "which state to delete?"
    rm $STORAGE""$2
    exit 0;
fi

# RENAME state
if [ $1 = "mv" ]; then 
    exists "$2" "which state to rename?"
    OLD=$STORAGE""$2
    exists "$3" "what to rename it to?"
    NEW=$STORAGE""$#
    if [ -e $NEW  ]; then
        echo "mpdstate $3 already exists, to overwrite it please delete it first.";
        exit 1;
    fi
    mv "$OLD" "$NEW"
    exit 0;
fi

# there were no argumets
echo "wrong argumets."
exit 1;
