#!/bin/sh

STORAGE="$HOME/.local/share/mpdstates/"
# yes, this is a butchering of pipes and scripting.
MPDSTATE=$(cat ~/.config/mpd/mpd.conf | grep -E "^state_file" | grep -o "\"/.*\"" | sed -e "s|\"||" -e "s|\"$||")
TMPFILE="/tmp/mpdstate.temp"

HELPSTRING=$(
cat << EOF
\tlo\tLoad (arg).\n
\tsa\tSave current state as (arg).\n
\tli\tList all saved states.\n
\tde\tDelete (arg) saved state."\n
EOF
)


echo 
# test if $1 is empty or not
exists(){
    if [ $1"" = "" ]; then 
        echo -e $2 
        exit 1
    fi
}

# the time it takes for mpd to start again
pause(){
    sleep 0.1
}

# make the storage if it doesn't exist
if [ ! -e $STORAGE ]; then 
    mkdir $STORAGE   
fi


exists "$1" "\tNeeds arguments,\n""$HELPSTRING"



# SAVE a playlist
if [ $1 = "sa" ]; then
    exists "$2" "needs name."    
    mpd --kill
    cp $MPDSTATE $STORAGE""$2
    pause
    mpd
    exit 0;
fi

# LOAD a playlist ()
if [ $1 = "lo" ]; then
    exists "$2" "which state to load?"    
    STATE=$STORAGE""$2
    if [ ! -e $STATE ]; then
        echo $2" doesn't exist."
        exit 0;
    fi
    mpd --kill
    cp $MPDSTATE $TMPFILE
    cp $STATE $MPDSTATE
    mv $TMPFILE $STORAGE"old"
    pause
    mpd
    exit 0;
fi

# LIST states
if [ $1 = "li" ]; then
    ls $STORAGE
    exit 0;
fi

# DELETE state
if [ $1 = "de" ]; then 
    exists "$2" "which state to delete?"
    rm $STORAGE""$2
fi

# there were no argumets
echo "wrong argumets."
exit 1;
